modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="deathbsod"
version="1.1.0"
displayName="DeathBSOD"
displayURL="https://github.com/RedstoneMaster011/bsod-on-death"
credits="RedstoneMaster01"
authors="RedstoneMaster01"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.deathbsod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration